apiVersion: apps/v1
kind: Deployment
metadata:
    name: chrona
spec:
    replicas: 2
    selector:
        matchLabels:
            service: chrona
    template:
        metadata:
            labels:
                service: chrona
        spec:
            containers:
                - env:
                      - name: SERVER_PORT
                        value: '3000'
                  image: zadoke/chrona:latest
                  imagePullPolicy: Always
                  name: chrona
                  ports:
                      - containerPort: 3000
                  resources: {}
            restartPolicy: Always
