apiVersion: apps/v1
kind: Deployment
metadata:
    name: cptrainbot-backend
spec:
    replicas: 2
    selector:
        matchLabels:
            service: cptrainbot-backend
    template:
        metadata:
            labels:
                service: cptrainbot-backend
        spec:
            containers:
                - env:
                      - name: SERVER_PORT
                        value: '3000'
                  image: zadoke/cptrainbot:backend
                  name: cptrainbot-backend
                  ports:
                      - containerPort: 3000
                  resources: {}
            restartPolicy: Always
